# Define your admin routes here
app.event_api:
    type: rest
    resource: App\Controller\Admin\EventController
    prefix: /admin/api
    name_prefix: app.

app.event_registration_api:
    type: rest
    resource: App\Controller\Admin\EventRegistrationController
    prefix: /admin/api
    name_prefix: app.

app.location_api:
    type: rest
    resource: App\Controller\Admin\LocationController
    prefix: /admin/api
    name_prefix: app.
